/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RechnerRouteImport } from './routes/rechner'
import { Route as PruefungRouteImport } from './routes/pruefung'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as LernenIndexRouteImport } from './routes/lernen.index'
import { Route as QuizIdRouteImport } from './routes/quiz.$id'
import { Route as LernenRegelnRouteImport } from './routes/lernen.regeln'
import { Route as LernenNatopaeckchenRouteImport } from './routes/lernen.natopaeckchen'
import { Route as LernenKampfrucksackRouteImport } from './routes/lernen.kampfrucksack'
import { Route as LernenAbcmaskeRouteImport } from './routes/lernen.abcmaske'
import { Route as LernenDienstgradeIndexRouteImport } from './routes/lernen.dienstgrade.index'
import { Route as LernenAusruestungIndexRouteImport } from './routes/lernen.ausruestung.index'
import { Route as LernenDienstgradeIdRouteImport } from './routes/lernen.dienstgrade.$id'
import { Route as LernenAusruestungIdRouteImport } from './routes/lernen.ausruestung.$id'

const RechnerRoute = RechnerRouteImport.update({
  id: '/rechner',
  path: '/rechner',
  getParentRoute: () => rootRouteImport,
} as any)
const PruefungRoute = PruefungRouteImport.update({
  id: '/pruefung',
  path: '/pruefung',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const LernenIndexRoute = LernenIndexRouteImport.update({
  id: '/lernen/',
  path: '/lernen/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdRoute = QuizIdRouteImport.update({
  id: '/quiz/$id',
  path: '/quiz/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LernenRegelnRoute = LernenRegelnRouteImport.update({
  id: '/lernen/regeln',
  path: '/lernen/regeln',
  getParentRoute: () => rootRouteImport,
} as any)
const LernenNatopaeckchenRoute = LernenNatopaeckchenRouteImport.update({
  id: '/lernen/natopaeckchen',
  path: '/lernen/natopaeckchen',
  getParentRoute: () => rootRouteImport,
} as any)
const LernenKampfrucksackRoute = LernenKampfrucksackRouteImport.update({
  id: '/lernen/kampfrucksack',
  path: '/lernen/kampfrucksack',
  getParentRoute: () => rootRouteImport,
} as any)
const LernenAbcmaskeRoute = LernenAbcmaskeRouteImport.update({
  id: '/lernen/abcmaske',
  path: '/lernen/abcmaske',
  getParentRoute: () => rootRouteImport,
} as any)
const LernenDienstgradeIndexRoute = LernenDienstgradeIndexRouteImport.update({
  id: '/lernen/dienstgrade/',
  path: '/lernen/dienstgrade/',
  getParentRoute: () => rootRouteImport,
} as any)
const LernenAusruestungIndexRoute = LernenAusruestungIndexRouteImport.update({
  id: '/lernen/ausruestung/',
  path: '/lernen/ausruestung/',
  getParentRoute: () => rootRouteImport,
} as any)
const LernenDienstgradeIdRoute = LernenDienstgradeIdRouteImport.update({
  id: '/lernen/dienstgrade/$id',
  path: '/lernen/dienstgrade/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LernenAusruestungIdRoute = LernenAusruestungIdRouteImport.update({
  id: '/lernen/ausruestung/$id',
  path: '/lernen/ausruestung/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profil': typeof ProfilRoute
  '/pruefung': typeof PruefungRoute
  '/rechner': typeof RechnerRoute
  '/lernen/abcmaske': typeof LernenAbcmaskeRoute
  '/lernen/kampfrucksack': typeof LernenKampfrucksackRoute
  '/lernen/natopaeckchen': typeof LernenNatopaeckchenRoute
  '/lernen/regeln': typeof LernenRegelnRoute
  '/quiz/$id': typeof QuizIdRoute
  '/lernen/': typeof LernenIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/lernen/ausruestung/$id': typeof LernenAusruestungIdRoute
  '/lernen/dienstgrade/$id': typeof LernenDienstgradeIdRoute
  '/lernen/ausruestung/': typeof LernenAusruestungIndexRoute
  '/lernen/dienstgrade/': typeof LernenDienstgradeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profil': typeof ProfilRoute
  '/pruefung': typeof PruefungRoute
  '/rechner': typeof RechnerRoute
  '/lernen/abcmaske': typeof LernenAbcmaskeRoute
  '/lernen/kampfrucksack': typeof LernenKampfrucksackRoute
  '/lernen/natopaeckchen': typeof LernenNatopaeckchenRoute
  '/lernen/regeln': typeof LernenRegelnRoute
  '/quiz/$id': typeof QuizIdRoute
  '/lernen': typeof LernenIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/lernen/ausruestung/$id': typeof LernenAusruestungIdRoute
  '/lernen/dienstgrade/$id': typeof LernenDienstgradeIdRoute
  '/lernen/ausruestung': typeof LernenAusruestungIndexRoute
  '/lernen/dienstgrade': typeof LernenDienstgradeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profil': typeof ProfilRoute
  '/pruefung': typeof PruefungRoute
  '/rechner': typeof RechnerRoute
  '/lernen/abcmaske': typeof LernenAbcmaskeRoute
  '/lernen/kampfrucksack': typeof LernenKampfrucksackRoute
  '/lernen/natopaeckchen': typeof LernenNatopaeckchenRoute
  '/lernen/regeln': typeof LernenRegelnRoute
  '/quiz/$id': typeof QuizIdRoute
  '/lernen/': typeof LernenIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/lernen/ausruestung/$id': typeof LernenAusruestungIdRoute
  '/lernen/dienstgrade/$id': typeof LernenDienstgradeIdRoute
  '/lernen/ausruestung/': typeof LernenAusruestungIndexRoute
  '/lernen/dienstgrade/': typeof LernenDienstgradeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profil'
    | '/pruefung'
    | '/rechner'
    | '/lernen/abcmaske'
    | '/lernen/kampfrucksack'
    | '/lernen/natopaeckchen'
    | '/lernen/regeln'
    | '/quiz/$id'
    | '/lernen/'
    | '/quiz/'
    | '/lernen/ausruestung/$id'
    | '/lernen/dienstgrade/$id'
    | '/lernen/ausruestung/'
    | '/lernen/dienstgrade/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profil'
    | '/pruefung'
    | '/rechner'
    | '/lernen/abcmaske'
    | '/lernen/kampfrucksack'
    | '/lernen/natopaeckchen'
    | '/lernen/regeln'
    | '/quiz/$id'
    | '/lernen'
    | '/quiz'
    | '/lernen/ausruestung/$id'
    | '/lernen/dienstgrade/$id'
    | '/lernen/ausruestung'
    | '/lernen/dienstgrade'
  id:
    | '__root__'
    | '/'
    | '/profil'
    | '/pruefung'
    | '/rechner'
    | '/lernen/abcmaske'
    | '/lernen/kampfrucksack'
    | '/lernen/natopaeckchen'
    | '/lernen/regeln'
    | '/quiz/$id'
    | '/lernen/'
    | '/quiz/'
    | '/lernen/ausruestung/$id'
    | '/lernen/dienstgrade/$id'
    | '/lernen/ausruestung/'
    | '/lernen/dienstgrade/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfilRoute: typeof ProfilRoute
  PruefungRoute: typeof PruefungRoute
  RechnerRoute: typeof RechnerRoute
  LernenAbcmaskeRoute: typeof LernenAbcmaskeRoute
  LernenKampfrucksackRoute: typeof LernenKampfrucksackRoute
  LernenNatopaeckchenRoute: typeof LernenNatopaeckchenRoute
  LernenRegelnRoute: typeof LernenRegelnRoute
  QuizIdRoute: typeof QuizIdRoute
  LernenIndexRoute: typeof LernenIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
  LernenAusruestungIdRoute: typeof LernenAusruestungIdRoute
  LernenDienstgradeIdRoute: typeof LernenDienstgradeIdRoute
  LernenAusruestungIndexRoute: typeof LernenAusruestungIndexRoute
  LernenDienstgradeIndexRoute: typeof LernenDienstgradeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rechner': {
      id: '/rechner'
      path: '/rechner'
      fullPath: '/rechner'
      preLoaderRoute: typeof RechnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pruefung': {
      id: '/pruefung'
      path: '/pruefung'
      fullPath: '/pruefung'
      preLoaderRoute: typeof PruefungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen/': {
      id: '/lernen/'
      path: '/lernen'
      fullPath: '/lernen/'
      preLoaderRoute: typeof LernenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$id': {
      id: '/quiz/$id'
      path: '/quiz/$id'
      fullPath: '/quiz/$id'
      preLoaderRoute: typeof QuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen/regeln': {
      id: '/lernen/regeln'
      path: '/lernen/regeln'
      fullPath: '/lernen/regeln'
      preLoaderRoute: typeof LernenRegelnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen/natopaeckchen': {
      id: '/lernen/natopaeckchen'
      path: '/lernen/natopaeckchen'
      fullPath: '/lernen/natopaeckchen'
      preLoaderRoute: typeof LernenNatopaeckchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen/kampfrucksack': {
      id: '/lernen/kampfrucksack'
      path: '/lernen/kampfrucksack'
      fullPath: '/lernen/kampfrucksack'
      preLoaderRoute: typeof LernenKampfrucksackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen/abcmaske': {
      id: '/lernen/abcmaske'
      path: '/lernen/abcmaske'
      fullPath: '/lernen/abcmaske'
      preLoaderRoute: typeof LernenAbcmaskeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen/dienstgrade/': {
      id: '/lernen/dienstgrade/'
      path: '/lernen/dienstgrade'
      fullPath: '/lernen/dienstgrade/'
      preLoaderRoute: typeof LernenDienstgradeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen/ausruestung/': {
      id: '/lernen/ausruestung/'
      path: '/lernen/ausruestung'
      fullPath: '/lernen/ausruestung/'
      preLoaderRoute: typeof LernenAusruestungIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen/dienstgrade/$id': {
      id: '/lernen/dienstgrade/$id'
      path: '/lernen/dienstgrade/$id'
      fullPath: '/lernen/dienstgrade/$id'
      preLoaderRoute: typeof LernenDienstgradeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lernen/ausruestung/$id': {
      id: '/lernen/ausruestung/$id'
      path: '/lernen/ausruestung/$id'
      fullPath: '/lernen/ausruestung/$id'
      preLoaderRoute: typeof LernenAusruestungIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfilRoute: ProfilRoute,
  PruefungRoute: PruefungRoute,
  RechnerRoute: RechnerRoute,
  LernenAbcmaskeRoute: LernenAbcmaskeRoute,
  LernenKampfrucksackRoute: LernenKampfrucksackRoute,
  LernenNatopaeckchenRoute: LernenNatopaeckchenRoute,
  LernenRegelnRoute: LernenRegelnRoute,
  QuizIdRoute: QuizIdRoute,
  LernenIndexRoute: LernenIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
  LernenAusruestungIdRoute: LernenAusruestungIdRoute,
  LernenDienstgradeIdRoute: LernenDienstgradeIdRoute,
  LernenAusruestungIndexRoute: LernenAusruestungIndexRoute,
  LernenDienstgradeIndexRoute: LernenDienstgradeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
